import { useState, useCallback } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import type { ChatMessage, ChatRequest, ChatResponse } from "@/lib/types";

/**
 * Custom hook for managing a chat conversation.
 *
 * This combines React's useState (for the message history) with
 * React Query's useMutation (for the API call lifecycle).
 *
 * useMutation is the right choice here because:
 * - Chat is a POST (it creates/changes data), not a GET
 * - We don't want caching -- each message is unique
 * - We DO want loading states, error handling, and retry logic
 *
 * Usage:
 *   const { messages, sendMessage, isPending, error } = useChat("model", "conv-id");
 */
export function useChat(model: string, conversationId: string | null) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: async (updatedMessages: ChatMessage[]) => {
      const payload: ChatRequest = {
        model,
        messages: updatedMessages,
        conversation_id: conversationId!,
      };
      const response = await api.post<ChatResponse>("/api/chat", payload);
      return response.data;
    },
    onSuccess: () => {
      // Invalidate conversations list so the sidebar picks up
      // updated timestamps and newly generated titles
      queryClient.invalidateQueries({ queryKey: ["conversations"] });

      // The title is generated by a background task on the server
      // after the first exchange, so it won't be ready when the
      // immediate invalidation fires. Re-invalidate after a delay
      // to pick up the newly generated title.
      setTimeout(() => {
        queryClient.invalidateQueries({ queryKey: ["conversations"] });
      }, 5000);
    },
  });

  const sendMessage = useCallback(
    (content: string) => {
      // Create the new user message
      const userMessage: ChatMessage = { role: "user", content };

      // Optimistically add the user message to the UI immediately
      const updatedMessages = [...messages, userMessage];
      setMessages(updatedMessages);

      // Fire the API call with the full conversation history
      mutation.mutate(updatedMessages, {
        onSuccess: (data) => {
          // Append the assistant's response to the conversation
          setMessages((prev) => [...prev, data.message]);
        },
      });
    },
    [messages, mutation]
  );

  /**
   * Seed the messages state with an existing conversation's messages.
   * Used when loading a conversation from the sidebar.
   */
  const seedMessages = useCallback((msgs: ChatMessage[]) => {
    setMessages(msgs);
  }, []);

  const clearMessages = useCallback(() => {
    setMessages([]);
    mutation.reset();
  }, [mutation]);

  return {
    messages,
    sendMessage,
    clearMessages,
    seedMessages,
    isPending: mutation.isPending,
    error: mutation.error,
  };
}
