from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.database import get_db
from app.models import Conversation, Message


router = APIRouter()


# --- Pydantic schemas ---


class CreateConversationRequest(BaseModel):
    """Request body for creating a new conversation."""

    model: str


class MessageOut(BaseModel):
    """Serialized message returned in conversation detail."""

    id: str
    role: str
    content: str
    created_at: str


class ConversationOut(BaseModel):
    """Serialized conversation returned in list responses (no messages)."""

    id: str
    title: str | None
    model: str
    created_at: str
    updated_at: str


class ConversationDetailOut(ConversationOut):
    """Serialized conversation with its full message history."""

    messages: list[MessageOut]


# --- Routes ---


@router.get("/conversations", response_model=list[ConversationOut])
async def list_conversations(db: AsyncSession = Depends(get_db)):
    """
    List all conversations ordered by most recently updated.

    Returns metadata only (no messages) for the sidebar list.
    """
    result = await db.execute(
        select(Conversation).order_by(Conversation.updated_at.desc())
    )
    convos = result.scalars().all()

    return [
        ConversationOut(
            id=c.id,
            title=c.title,
            model=c.model,
            created_at=c.created_at.isoformat(),
            updated_at=c.updated_at.isoformat(),
        )
        for c in convos
    ]


@router.post("/conversations", response_model=ConversationOut, status_code=201)
async def create_conversation(
    request: CreateConversationRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Create a new empty conversation.

    Called when the user starts a new chat. The title will be
    generated by the LLM after the first message exchange.
    """
    conversation = Conversation(model=request.model)
    db.add(conversation)
    await db.flush()

    return ConversationOut(
        id=conversation.id,
        title=conversation.title,
        model=conversation.model,
        created_at=conversation.created_at.isoformat(),
        updated_at=conversation.updated_at.isoformat(),
    )


@router.get("/conversations/{conversation_id}", response_model=ConversationDetailOut)
async def get_conversation(
    conversation_id: str,
    db: AsyncSession = Depends(get_db),
):
    """
    Get a single conversation with all its messages.

    Used when resuming/reviewing a past conversation.
    """
    result = await db.execute(
        select(Conversation)
        .where(Conversation.id == conversation_id)
        .options(selectinload(Conversation.messages))
    )
    conversation = result.scalar_one_or_none()

    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")

    return ConversationDetailOut(
        id=conversation.id,
        title=conversation.title,
        model=conversation.model,
        created_at=conversation.created_at.isoformat(),
        updated_at=conversation.updated_at.isoformat(),
        messages=[
            MessageOut(
                id=m.id,
                role=m.role,
                content=m.content,
                created_at=m.created_at.isoformat(),
            )
            for m in conversation.messages
        ],
    )


@router.delete("/conversations/{conversation_id}", status_code=204)
async def delete_conversation(
    conversation_id: str,
    db: AsyncSession = Depends(get_db),
):
    """
    Delete a conversation and all its messages.

    The cascade delete is handled by the ORM relationship
    (cascade='all, delete-orphan' on Conversation.messages).
    """
    result = await db.execute(
        select(Conversation).where(Conversation.id == conversation_id)
    )
    conversation = result.scalar_one_or_none()

    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")

    await db.delete(conversation)
